<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-U5UN98U" failures="2" tests="2" name="Test(failed)(failed)(failed)" time="2.106" errors="0" timestamp="2022-03-22T15:00:02 GMT-04:00">
  <testcase classname="testNG_XML_lStudy.FailedXMLStudy" name="TC4" time="0.016">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testNG_XML_lStudy.FailedXMLStudy.TC4(FailedXMLStudy.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TC4 -->
  <testcase classname="testNG_XML_lStudy.FailedXMLStudy" name="TC1" time="2.016">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method testNG_XML_lStudy.FailedXMLStudy.TC1() didn&amp;apos;t finish within the time-out 2000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testNG_XML_lStudy.FailedXMLStudy.TC1() didn't finish within the time-out 2000
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- TC1 -->
  <testcase classname="testNG_XML_lStudy.FailedXMLStudy" name="TC3" time="0.0">
    <ignored/>
  </testcase> <!-- TC3 -->
  <testcase classname="testNG_XML_lStudy.FailedXMLStudy" name="TC5" time="0.0">
    <ignored/>
  </testcase> <!-- TC5 -->
  <testcase classname="testNG_XML_lStudy.FailedXMLStudy" name="TC2" time="0.0">
    <ignored/>
  </testcase> <!-- TC2 -->
</testsuite> <!-- Test(failed)(failed)(failed) -->
